#!/usr/bin/env bash

# Only start nginx if he WEB_PROCESS_CMD is defined
if [ -f .nginx/bin/nginx-start ] && [ -n "$WEB_PROCESS_CMD" ]; then
  cd .nginx > /dev/null 2>&1
  eval "bin/nginx-start &"
  pid=$!
  cd - > /dev/null 2>&1
  trap "kill -9 $pid; exit" SIGKILL
else
  echo "No .nginx/bin/nginx-start file found!"
fi
